baseURL: "https://blog.neatio.net"
languageCode: en-us
theme: ["hugo-notice"]
paginate: 5
title: "Neatio"
copyright: "© 2022  Neatio"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
googleAnalytics: "G-1ZN2JNL2H3"
ignoreErrors:
  - error-remote-getjson
minify:
  disableXML: true
  minifyOutput: true
##################################################################
params:
  env: production
  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: /favicon/favicon.ico
    favicon16x16: /favicon/favicon-16x16.png
    favicon32x32: /favicon/favicon-32x32.png
    apple_touch_icon: /favicon/apple-touch-icon.png
    safari_pinned_tab: /favicon/mstile-144x144.png
  images:
    - /img/social.jpg # This is the root pic when sharing on social media
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: ""

  author: "Neatio"
  description: "A collection of walkthroughs, rants, and hacks on emerging cloud technologies and DevOps methodology and tools."
  comments: true
  mainSections:
    - post
    - posts
  keywords: [DevOps, Neat, Neatio, Cloud, Linux, tech, Blog, Golan, Development, docker, kubernetes, Ansible]
  label:
    text: NeatBlog # sets the top left blue "home" link text
    icon: /img/logo.png
    iconHeight: 35
  defaultTheme: auto
  ShowBreadCrumbs: true
  disableThemeToggle: false
  ShowPostNavLinks: true
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  disableAnchoredHeadings: true
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  TocOpen: false
  disableScrollToTop: true
  ShowRssButtonInSectionTermList: false
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true
    linkFullImages: true
  schema:
    publisherType: Website
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "content"]
  privacy:
    instagram:
      disable: false
      simple: true
    twitter:
      disable: false
      enableDNT: false
      simple: true
    vimeo:
      disable: false
      simple: true
    youtube:
      disable: false
      privacyEnhanced: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: false
    lineNos: false
    style: dracula
menu:
  main:
    - name: Blog
      url: /posts/
      weight: 10
    - identifier: categories
      name: Series
      url: /categories/
      weight: 20
    # - name: Projects
    #   url: projects
    #   weight: 30
    # - name: About
    #   url: /about
    #   weight: 40
    - identifier: search
      post: <svg width="23" height="23" viewBox="0 0 30 13" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M18.319 14.4326C20.7628 11.2941 20.542 6.75347 17.6569 3.86829C14.5327 0.744098 9.46734 0.744098 6.34315 3.86829C3.21895 6.99249 3.21895 12.0578 6.34315 15.182C9.22833 18.0672 13.769 18.2879 16.9075 15.8442C16.921 15.8595 16.9351 15.8745 16.9497 15.8891L21.1924 20.1317C21.5829 20.5223 22.2161 20.5223 22.6066 20.1317C22.9971 19.7412 22.9971 19.1081 22.6066 18.7175L18.364 14.4749C18.3493 14.4603 18.3343 14.4462 18.319 14.4326ZM16.2426 5.28251C18.5858 7.62565 18.5858 11.4246 16.2426 13.7678C13.8995 16.1109 10.1005 16.1109 7.75736 13.7678C5.41421 11.4246 5.41421 7.62565 7.75736 5.28251C10.1005 2.93936 13.8995 2.93936 16.2426 5.28251Z" fill="currentColor" /></svg>
      url: /search
      weight: 50
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search to work
