name = "newsroom"
license = "MIT"
description = "A simple open source theme for publishing multi-purpose content"
tags = ["blog", "simple", "dark", "minimalist", "fast", "disqus", "syntax highlighting"]
features = ["blog", "simple", "dark", "minimalist", "fast", "disqus", "syntax highlighting"]
min_version = "0.63.0"

[author]
    name ="tizu"
    homepage = "https://github.com/mrtizu"
